### ISSUE TITLE
Container registry defaults on version checks.

### ISSUE THREAD

**Issue by timothysc** [heptio/sonobuoy#562] opened 2018-12-04 19:19 UTC
We will need to pull the gcr.io based kube-conformance container for detected versions > 1.13 

Poke @liztio in case you have questions.

**Comment by johnSchnake** [comment] 2019-03-07 14:40
This seems to be a duplicate of the ticket I just closed and seems to further validate that this is referencing using the upstream conformance image (which started getting published in 1.13). Closing as duplicate of #593

**Closed by johnSchnake** 2019-03-07 14:40 UTC
