### ISSUE TITLE
Feature Request: command to print passed/failed & completed/total

### ISSUE THREAD

**Issue by karlkfi** [heptio/sonobuoy#422] opened 2018-05-11 19:35 UTC
Use cases:
1. While the tests are running, I want to see status/progress in terms of completed and total tests while the tests are still running.
2. While the tests are running, I want to know if a test failed before the test suite completes so that I can get early feedback and decide whether I need to keep running the tests (maybe they're all failing because a component is unhealthy or there's not enough resources).
3. When the tests are complete, I want to know whether the tests succeeded or failed without having to retrieve the whole bundle with a ton of files I don't want or the whole log.

I expected `sononbuoy status` to do this, but it shows the status of sonobuoy itself, not the status of the tests...

So maybe a new `sonobuoy results` command could print:
- suite name (not sure how this would work with plugins)
- total
- completed
- passed
- failed
- skipped

**Comment by stevesloka** [comment] 2019-02-20 21:08
Similar to #354

**Comment by johnSchnake** [comment] 2019-02-20 21:09
As far as item 3 goes; there is now a `sonobuoy e2e` command which can read the results of the e2e plugin from a `.tar.gz` file so you can see the number passed/failed.

**Comment by johnSchnake** [comment] 2019-05-28 20:25
Going to close this as duplicate.

The request for progress is duplicate of #354 
The other output, its a duplicate of #306

**Closed by johnSchnake** 2019-05-28 20:25 UTC
Labels: Needs Product, p1 - Important
