### ISSUE TITLE
Create a release puchnlist

### ISSUE THREAD

**Issue by chuckha** [heptio/sonobuoy#524] opened 2018-08-17 19:26 UTC

**Comment by timothysc** [comment] 2018-09-21 16:33
Ideally automation fixes most of this and our punchlist is minimal.

**Comment by timothysc** [comment] 2018-09-21 16:33
I'll PR some extra verification steps.

**Comment by stevesloka** [comment] 2019-02-20 20:12
Duplicate of #409

**Closed by stevesloka** 2019-02-20 20:12 UTC
Labels: p0 - Higher Priority
