### ISSUE TITLE
`--e2e-repo-config` is apparently ignored

### ISSUE THREAD

**Issue by andrewmyhre** [heptio/sonobuoy#653] opened 2019-04-02 12:28 UTC
**What steps did you take and what happened:**

We work in an airgapped environment where public docker repositories are blocked and images can only be pulled from our Artifactory servers. The team managing our Artifactory cluster have set up mirrors for common public repositories like `k8s.gcr.io`, `gcr.io` and `quay.io`.

The documentation says this scenario is supported. By creating a file like this:
```
dockerLibraryRegistry: artifactory.cloud.ourcompany.com/heptio-sonobuoy
e2eRegistry: artifactory-gcr-dev.clouddqt.ourcompany.com/kubernetes-e2e-test-images
gcRegistry: artifactory-k8sgcr-dev.clouddqt.ourcompany.com
etcdRegistry: artifactory-quay.cloud.ourcompany.com/coreos
privateRegistry: artifactory-gcr-dev.clouddqt.ourcompany.com/k8s-authenticated-test
sampleRegistry: artifactory-gcr-dev.clouddqt.ourcompany.com/google-samples
```

And run sonobuoy like this:
```
sonobuoy run --e2e-repo-config=sonobuoy-custom-repos.yaml --sonobuoy-image=artifactory-gcr-dev.clouddqt.ourcompany.com/heptio-images/sonobuoy:v0.14.0
```

After a few seconds I see a number of systemd pods:

```
ks get pods
NAME                                                      READY   STATUS              RESTARTS   AGE
sonobuoy                                                  1/1     Running             0          18s
sonobuoy-e2e-job-1858553517684a40                         0/2     ContainerCreating   0          16s
sonobuoy-systemd-logs-daemon-set-5003cdb4678e48ea-465rt   0/2     ContainerCreating   0          16s
sonobuoy-systemd-logs-daemon-set-5003cdb4678e48ea-58x7p   0/2     ContainerCreating   0          16s
sonobuoy-systemd-logs-daemon-set-5003cdb4678e48ea-69ndl   0/2     ContainerCreating   0          16s
sonobuoy-systemd-logs-daemon-set-5003cdb4678e48ea-9j8th   0/2     ContainerCreating   0          16s
sonobuoy-systemd-logs-daemon-set-5003cdb4678e48ea-bzb84   1/2     ErrImagePull        0          16s
sonobuoy-systemd-logs-daemon-set-5003cdb4678e48ea-g5dnw   0/2     ContainerCreating   0          16s
sonobuoy-systemd-logs-daemon-set-5003cdb4678e48ea-j6wfm   0/2     ContainerCreating   0          16s
sonobuoy-systemd-logs-daemon-set-5003cdb4678e48ea-mhsw5   0/2     ContainerCreating   0          16s
sonobuoy-systemd-logs-daemon-set-5003cdb4678e48ea-q5htv   0/2     ContainerCreating   0          16s
sonobuoy-systemd-logs-daemon-set-5003cdb4678e48ea-qh7vg   0/2     ContainerCreating   0          16s
sonobuoy-systemd-logs-daemon-set-5003cdb4678e48ea-qlwmj   0/2     ContainerCreating   0          16s
```

Describing them I see they're pulling from the public repo, not the repo I've provided:
```
Events:
  Type     Reason     Age   From                                    Message
  ----     ------     ----  ----                                    -------
  Normal   Scheduled  19s   default-scheduler                       Successfully assigned heptio-sonobuoy/sonobuoy-systemd-logs-daemon-set-5003cdb4678e48ea-69ndl to ip-10-205-233-62.ec2.internal
  Normal   Pulling    18s   kubelet, ip-10-205-233-62.ec2.internal  pulling image "gcr.io/heptio-images/sonobuoy-plugin-systemd-logs:latest"
  Warning  Failed     3s    kubelet, ip-10-205-233-62.ec2.internal  Failed to pull image "gcr.io/heptio-images/sonobuoy-plugin-systemd-logs:latest": rpc error: code = Unknown desc = Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Failed     3s    kubelet, ip-10-205-233-62.ec2.internal  Error: ErrImagePull
  Normal   Pulled     3s    kubelet, ip-10-205-233-62.ec2.internal  Container image "artifactory-gcr-dev.clouddqt.ourcompany.com/heptio-images/sonobuoy:v0.14.0" already present on machine
  Normal   Created    3s    kubelet, ip-10-205-233-62.ec2.internal  Created container
  Normal   Started    3s    kubelet, ip-10-205-233-62.ec2.internal  Started container
  Normal   BackOff    2s    kubelet, ip-10-205-233-62.ec2.internal  Back-off pulling image "gcr.io/heptio-images/sonobuoy-plugin-systemd-logs:latest"
  Warning  Failed     2s    kubelet, ip-10-205-233-62.ec2.internal  Error: ImagePullBackOff
```

**What did you expect to happen:**
The `sonobuoy-plugin-systemd-logs` image would be pulled from our `gcr.io` mirror.

**Environment:**

- Sonobuoy version: v0.14.0
- Kubernetes version: (use `kubectl version`): v1.13.1
- Kubernetes installer & version: custom
- Cloud provider or hardware configuration: AWS EC2
- OS (e.g. from `/etc/os-release`):  Ubunutu
- Sonobuoy tarball (which contains * below)

**Comment by andrewmyhre** [comment] 2019-04-02 12:56
I realized this was because I wasn't overriding the conformance pod and it's not possible to specify image repos for tests other than the e2e tests.

**Comment by andrewmyhre** [comment] 2019-04-02 13:01
It does seem like it's being ignored:

```
STEP: Creating a pod to test consume configMaps
Apr  2 12:59:30.303: INFO: Waiting up to 5m0s for pod "pod-projected-configmaps-2752fe28-5547-11e9-b60f-de47be121f06" in namespace "e2e-tests-projected-np2rf" to be "success or failure"
Apr  2 12:59:30.306: INFO: Pod "pod-projected-configmaps-2752fe28-5547-11e9-b60f-de47be121f06": Phase="Pending", Reason="", readiness=false. Elapsed: 2.887849ms
```

```
kubectl -n e2e-tests-projected-np2rf get pods
NAME                                                            READY   STATUS             RESTARTS   AGE
pod-projected-configmaps-2752fe28-5547-11e9-b60f-de47be121f06   0/1     ImagePullBackOff   0          35s
```

```
kubectl -n e2e-tests-projected-np2rf describe po pod-projected-configmaps-2752fe28-5547-11e9-b60f-de47be121f06
....
Events:
  Type     Reason     Age                From                                     Message
  ----     ------     ----               ----                                     -------
  Normal   Scheduled  41s                default-scheduler                        Successfully assigned e2e-tests-projected-np2rf/pod-projected-configmaps-2752fe28-5547-11e9-b60f-de47be121f06 to ip-10-205-233-231.ec2.internal
  Warning  Failed     25s                kubelet, ip-10-205-233-231.ec2.internal  Failed to pull image "gcr.io/kubernetes-e2e-test-images/mounttest:1.0": rpc error: code = Unknown desc = Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Failed     25s                kubelet, ip-10-205-233-231.ec2.internal  Error: ErrImagePull
  Normal   BackOff    25s                kubelet, ip-10-205-233-231.ec2.internal  Back-off pulling image "gcr.io/kubernetes-e2e-test-images/mounttest:1.0"
  Warning  Failed     25s                kubelet, ip-10-205-233-231.ec2.internal  Error: ImagePullBackOff
  Normal   Pulling    13s (x2 over 40s)  kubelet, ip-10-205-233-231.ec2.internal  pulling image "gcr.io/kubernetes-e2e-test-images/mounttest:1.0"
```

**Comment by johnSchnake** [comment] 2019-04-02 13:25
Thanks for the report; I will look into this right away. There have been cases of finding particular tests that dont pull from the right place but I think most of those have been found. @andrewmyhre can you clarify if you are seeing this happen on that one particular test/pod only or all of them?

There are a few different images at play so lets be clear about them (and I'll take a look at the documentation and see if it needs fixed up as well):

 - sonobuoy image - normally from gcr.io and can be overridden with the `--sonobuoy-image` flag
 - conformance image - normally from gcr.io and can be overridden with the `--conformance-image` flag; this is the wrapper _around_ the e2e tests so at this level nothing has consumed the `--e2e-repo-list` yet
 - test images - These images are from a few places and the conformance image will use the `--e2e-repo-config` to lookup where to find them

**Comment by stevesloka** [comment] 2019-04-02 13:27
Would be also good to confirm the `ImagePullPolicy` to make sure it's not `Always`.

**Comment by johnSchnake** [comment] 2019-04-02 13:32
@stevesloka but if it is `Always` and he's provided the override then it should pull from their location.

**Comment by johnSchnake** [comment] 2019-04-02 14:15
I'm trying to replicate this and so far I haven't been able to (it is still running). To try and be certain I set up mine in another failure condition: I used your repo list so every test _should_ fail due to being unable to pull. It takes a while because it has to let each of the 14 projected configmap tests timeout, but so far it hasn't used the default.

@andrewmyhre  Another thing that would be of interest is the output you get from this:
Get the e2e pod itself via (something like `sonobuoy-e2e-job-58b7bb7aeff3420e`:
```
kubectl get pods --all-namespaces|grep e2e
```

Then exec in that pod and check that the mount occurred as expected:
```
$ echo $KUBE_TEST_REPO_LIST
$ cat $KUBE_TEST_REPO_LIST
```

After that, just the general set of logs would be useful to see if sonobuoy/e2e complained for some reason about reading the file or mounting it etc etc. Again, a big part of this is also knowing if this happened to one of the tests or all of the tests.

**Comment by johnSchnake** [comment] 2019-04-02 15:40
Based on your logs I ran all the "Projected configMap" tests. There are 14 of them; even without the images, 2 tests pass because the _point_ of the test is to see that pod creation fails (it doesn't really check what the error is, so in my case it would be a timeout regardless, but it should have failed for another reason anyways).

All of the others failed for timeout, failing to pull the images from the registries that I specified in my registry overrides.

I was testing on a slightly newer cluster version (1.14.0) but I can spin up a 1.13.1 cluster and try again. If you can provide the full output from `kubectl version` it can help ensure I test the right version.

**Comment by johnSchnake** [comment] 2019-04-02 18:46
All the places where the image is set for the projected configmap tests (https://github.com/kubernetes/kubernetes/blame/master/test/e2e/common/projected_configmap.go) havent been changed in 6-8 months which would have been way before the 1.13 image.

I'll need some of the requested info to be able to diagnose any further.

**Comment by johnSchnake** [comment] 2019-04-15 18:29
@andrewmyhre are you still having this issue? I needed more info to help diagnose the problem. Let me know if it is no longer an issue for you.

**Comment by johnSchnake** [comment] 2019-04-25 20:56
Closing; please reopen if you can reproduce this error as it would be very important for us to investigate.

**Closed by johnSchnake** 2019-04-25 20:56 UTC
Labels: p0 - Higher Priority, waiting for info

**Comment by rackeric** [comment] 2019-07-10 22:10
Hello I am seeing this not work for me either right now. Here are some details. I am seeing this file and environment variable in the sonobuoy-e2e-job pod also.

Sonobuoy version: v0.14.3
Kubernetes version: (use kubectl version): v1.12.6
Kubernetes installer & version: kubeadm v1.12.6
Cloud provider or hardware configuration: bare metal
OS (e.g. from /etc/os-release): CentOS 7

```
[root@master001 sonobuoy_files_v0.14.3]# kubectl get pods --all-namespaces|grep e2e
e2e-tests-deployment-tq8nq   test-cleanup-controller-h9gb4                                 0/1     ImagePullBackOff   0          95s
heptio-sonobuoy              sonobuoy-e2e-job-4c6896081ebf4aa6                             2/2     Running            0          97s
[root@master001 sonobuoy_files_v0.14.3]# kubectl exec -it sonobuoy-e2e-job-4c6896081ebf4aa6 -n heptio-sonobuoy /bin/sh
Defaulting container name to e2e.
Use 'kubectl describe pod/sonobuoy-e2e-job-4c6896081ebf4aa6 -n heptio-sonobuoy' to see all of the containers in this pod.
# cat $KUBE_TEST_REPO_LIST
---
dockerLibraryRegistry: <removed>
e2eRegistry: <removed>
gcRegistry: <removed>
privateRegistry: <removed>
sampleRegistry: <removed>
etcdRegistry: <removed>
# exit
```

Yet, images continue to try to be pulled from their default locations:
```Normal   BackOff    4s (x2 over 5s)  kubelet, node001.<cluster>.applecloud.io  Back-off pulling image "gcr.io/kubernetes-e2e-test-images/mounttest:1.0"```
