### ISSUE TITLE
Error POST RESULT - 413

### ISSUE THREAD

**Issue by Talits** [heptio/sonobuoy#443] opened 2018-06-13 18:27 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG Report

**What happened**:
I have error 413 in POST to server heptio results - forwarder error, results are collected normally

time="2018-06-13T21:42:40Z" level=info msg="processing result file" result file=/tmp/sonobuoy/201806131827_sonobuoy_b1f1fe2c-2149-45be-9307-e3d554a55d31.tar.gz
time="2018-06-13T21:42:41Z" level=info msg="failed to POST data" endpoint="http://127.0.0.1:9898/ingest/" error="non success response code: 413" result file=/tmp/sonobuoy/201806131827_sonobuoy_b1f1fe2c-2149-45be-9307-e3d554a55d31.tar.gz

**What you expected to happen**:
I would like to see the result online

**How to reproduce it (as minimally and precisely as possible)**:
I has a cluster with many data, the process during 3hours, but not POST, I have changed timeout server 

**Anything else we need to know?**:

**Environment**:
- Sonobuoy tarball (which contains * below) 
- Kubernetes version (use `kubectl version`): v1.9.1
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): centos
- Kernel (e.g. `uname -a`): Linux 3.10.0-693.21.1.el7.x86_64

**Comment by timothysc** [comment] 2018-06-22 21:33
This is a 'too large error' - @chuckha

**Comment by caruccio** [comment] 2018-06-27 11:34
FYI, Pt. 2 - that 413 was being caused by a continuous CrashLoop which created a 76MB tar.gz.
If @Talits is ok with that we cloud close the issue.

**Closed** 2018-06-27 18:58 UTC
Labels: p1 - Important
