### ISSUE TITLE
Test Sonobuouy against local-up-cluster

### ISSUE THREAD

**Issue by chuckha** [heptio/sonobuoy#314] opened 2018-03-02 15:41 UTC
There seems to be some kind of issue running against a local-up-cluster. Here are some relevant pastes from the slack:

```
root@scspa0413866001:~# sonobuoy logs
INFO[0000] Printing container logs                       container=kube-sonobuoy pod=sonobuoy
ERRO[0000] error attempting to get sonobuoy logs: failed to stream logs: could not stream the request: the server could not find the requested resource ( pods/log sonobuoy)
```

```
root@scspa0413866001:~# kubectl get pods --all-namespaces
NAMESPACE                         NAME                        READY     STATUS    RESTARTS   AGE
e2e-tests-container-probe-2bgk8   liveness-exec               1/1       Running   116        17h
heptio-sonobuoy                   sonobuoy                    1/1       Running   0          15h
kube-system                       kube-dns-76f5594bd5-hzps2   3/3       Running   0          1d
```

**Comment by timothysc** [comment] 2018-03-02 15:45
We will likely need to PR against upstream for some of the defaults as well. 
e.g. `--allow-privileged=true` needs to be enabled.

**Comment by timothysc** [comment] 2018-03-02 19:46
Hi @timothysc - here’s where i am right now
1) KubeletManagedEtcHosts - PR 60627 in k/k
2) HostPath - currently looking, possibly something docker does not like when running in a DIND - `"mount --make-shared /"` i think)
3) Daemonset failures - there’s a PR about to merge in SQ (PR 60672 in k/k)

https://k8s-testgrid.appspot.com/sig-testing-misc#ci-kubernetes-local-e2e


dims [10:02 AM]
@timothysc on the `--privileged` by default for local-up-cluster, i was not sure that’s the right thing to do. so just made a temporary change in kubetest/local.go to set the flag to true there. discussion on (https://github.com/kubernetes/kubernetes/issues/59978)
GitHub
Conformance test "HostPath should give a volume the correct mode" needs privileged containers · Issue #59978 · kubernetes/kubernetes
Do we really want to mandate that to conform, a provider should allow privileged containers? Is this by design or by an oversight? [sig-storage] HostPath should give a volume the correct mode [C...

**Comment by timothysc** [comment] 2018-06-22 22:17
Closing this issue, I know there was work done to fix some things upstream, and overall importance from sonobuoy use cases is low.

**Closed by timothysc** 2018-06-22 22:17 UTC
Labels: fixupstream, p2 - Long-term Important
