### ISSUE TITLE
Need a formal conformance test report after testing execution

### ISSUE THREAD

**Issue by jwang11** [heptio/sonobuoy#792] opened 2019-07-03 01:35 UTC
**Describe the solution you'd like**
Currently, following the guide as below, I ran sonobuoy on a clear linux cluster ( 1 master node and 2 worker nodes)
```
sonobuoy run --wait
results=$(sonobuoy retrieve)
sonobuoy e2e $results
```
what I got is just the failed TC
```
failed tests: 1
[sig-storage] EmptyDir wrapper volumes should not cause race condition when used for configmaps [Serial] [Conformance]
```
It is too simple. I expect to get is a formal conformance test report, including total TCs, passed TC, passed TC.

By extract result file, e.g 201906120856_sonobuoy_a49c02de-5e20-424e-bb8b-4b9da7678ff6.tar.gz, I can see full log under /plugins/e2e/results/e2e.log. At the end of the log, I observe below information. Not sure it is what I expected test report, - 204 conformance TCs totally, 1 failed.
```
Summarizing 1 Failure:

[Fail] [sig-storage] EmptyDir wrapper volumes [It] should not cause race conditi
on when used for configmaps [Serial] [Conformance]
/workspace/anago-v1.14.3-beta.0.37+5e53fd6bc17c0d/src/k8s.io/kubernetes/_output/
dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/empty_dir_wrapper.go:424

Ran 204 of 3585 Specs in 6727.839 seconds
FAIL! -- 203 Passed | 1 Failed | 0 Pending | 3381 Skipped --- FAIL: TestE2E (672
8.10s)
FAIL
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
Sonobuoy Version: v0.14.3
MinimumKubeVersion: 1.12.0
MaximumKubeVersion: 1.14.99
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"archive", BuildDate:"2019-06-26T20:43:01Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: 1 master node + 2 worker nodes
- OS (e.g. from `/etc/os-release`): Clear Linux

**Comment by johnSchnake** [comment] 2019-07-03 13:40
So the `e2e` command does just give you a simple set of output that can easily be scripted around. You can pass the `--show` flag to see `passed` or `failed` commands as well to see a different set so you can do some basic scripting around how many passed/failed.

It seems like, in general, this is a duplicate of https://github.com/heptio/sonobuoy/issues/306

The `e2e` command was created a long time ago and wasn't generalized to work with other plugins at all. The plan is to work on 306 and get a `sonobuoy result` command that can have some different output options, understand the output from a few different plugin result types, and be able to work with any plugin in some capacity.

Going to close as duplicate; thanks for the feedback and ping on that issue though.

**Closed by johnSchnake** 2019-07-03 13:40 UTC
